#ifndef KEYMAP_H
#define KEYMAP_H

typedef enum KeymapAction
{
  KEYMAP_ACTION_CLOSE_APP = 0,
  KEYMAP_ACTION_TOGGLE_FULLSCREEN,
  KEYMAP_ACTION_TOGGLE_CURSOR_MODE,
  KEYMAP_ACTION_TOGGLE_PLAYER_MODE,
  KEYMAP_ACTION_TOGGLE_CYCLE,
  KEYMAP_ACTION_RESET_CYCLE,
  KEYMAP_ACTION_CYCLE_FASTER,
  KEYMAP_ACTION_CYCLE_SLOWER,
  KEYMAP_ACTION_MOVE_FORWARD,
  KEYMAP_ACTION_MOVE_BACKWARD,
  KEYMAP_ACTION_MOVE_LEFT,
  KEYMAP_ACTION_MOVE_RIGHT,
  KEYMAP_ACTION_JUMP,
  KEYMAP_ACTION_MOVE_DOWN,
  KEYMAP_ACTION_MOVE_FAST,
  KEYMAP_ACTION_SCRUB_BACKWARD,
  KEYMAP_ACTION_SCRUB_FORWARD,
  KEYMAP_ACTION_BREAK_BLOCK,
  KEYMAP_ACTION_PLACE_BLOCK,
  KEYMAP_ACTION_BLOCK_SLOT_1,
  KEYMAP_ACTION_BLOCK_SLOT_2,
  KEYMAP_ACTION_BLOCK_SLOT_3,
  KEYMAP_ACTION_BLOCK_SLOT_4,
  KEYMAP_ACTION_COUNT
} KeymapAction;

int keymap_get_primary_virtual_key(KeymapAction action);
int keymap_get_secondary_virtual_key(KeymapAction action);
int keymap_get_block_slot_index(KeymapAction action);

#endif
